@startuml

top to bottom direction
skinparam linetype ortho

interface BaseModelService<M, E> << interface >> {
  + create(M): M
  + getById(Long): M
  + update(M): M
  + createAll(List<M>): List<M>
   all: List<M>
}
class BaseModelServiceImpl<M, E> {
  # BaseModelServiceImpl():
  + getById(Long): M
  + update(Object): M
  + create(M): M
  + createAll(List<M>): List<M>
   all: List<M>
   modelMapper: ModelMapper
   jpaRepository: JpaRepository<E, Long>
}
interface BranchOfficeService << interface >>
class BranchOfficeServiceImpl {
  + BranchOfficeServiceImpl(BranchOfficeRepository, ModelMapper):
  - modelMapper: ModelMapper
   modelMapper: ModelMapper
   jpaRepository: JpaRepository
}

BaseModelServiceImpl     -[#008200,dashed]-^  BaseModelService
BranchOfficeService      -[#008200,plain]-^  BaseModelService
BranchOfficeServiceImpl  -[#000082,plain]-^  BaseModelServiceImpl
BranchOfficeServiceImpl  -[#008200,dashed]-^  BranchOfficeService
@enduml
