@startuml

top to bottom direction
skinparam linetype ortho

interface BaseModelService<M, E> << interface >> {
  + create(M): M
  + getById(Long): M
  + update(M): M
  + createAll(List<M>): List<M>
   all: List<M>
}
class BaseModelServiceImpl<M, E> {
  # BaseModelServiceImpl():
  + getById(Long): M
  + update(Object): M
  + create(M): M
  + createAll(List<M>): List<M>
   all: List<M>
   modelMapper: ModelMapper
   jpaRepository: JpaRepository<E, Long>
}
interface UserService << interface >> {
  + login(String, String): User
}
class UserServiceImpl {
  + UserServiceImpl(UserRepository, ModelMapper):
  - modelMapper: ModelMapper
  + login(String, String): User
   modelMapper: ModelMapper
   jpaRepository: JpaRepository
}

BaseModelServiceImpl  -[#008200,dashed]-^  BaseModelService
UserService           -[#008200,plain]-^  BaseModelService
UserServiceImpl       -[#000082,plain]-^  BaseModelServiceImpl
UserServiceImpl       -[#008200,dashed]-^  UserService
@enduml
